[build]
  command = "npm run build"
  publish = "out"
[[plugins]]
package = "netlify-plugin-is-website-vulnerable"

# Use double brackets since `plugins` is an array of tables.
[[context.production.plugins]]
package = "@netlify/plugin-sitemap"

[[plugings]]
package = "@netlify/plugin-nextjs"

