[build]
  command = "npm run build && npm run export"
  publish = ".next"
[[plugins]]
package = "netlify-plugin-is-website-vulnerable"

# Use double brackets since `plugins` is an array of tables.
[[context.production.plugins]]
package = "@netlify/plugin-sitemap"

[[plugings]]
package = "@netlify/plugin-nextjs"

functions = "netlify/functions"
edge-functions = "netlify/edge-functions"
